useDotenv: true

service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  profile: aws-training
  environment:
    DB_PRODUCTS: ${self:custom.dotenvVars.DB_PRODUCTS, env:DB_PRODUCTS, ''}
    DB_STOCKS: ${self:custom.dotenvVars.DB_STOCKS, env:DB_STOCKS, ''}
    SNS_ARN: 
      Ref: createProductTopic
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - Fn::GetAtt: [catalogItemsQueue, Arn]
    - Effect: Allow
      Action:
        - sns:*
      Resource:
        Ref: createProductTopic

resources:
  Resources:
    catalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalog-items-queue
    createProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: create-product-topic
    createProductTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: vlad.fps@gmail.com
        Protocol: email
        TopicArn:
          Ref: createProductTopic
  Outputs:
      sqsUrl:
        Value: !Ref catalogItemsQueue
      sqsArn:
        Value:
          Fn::GetAtt: [catalogItemsQueue, Arn]


custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
    dotenvVars: ${file(configs.mjs)}

functions:
  getProductList:
    handler: handler.getProductList
    events:
      - http:
          method: get
          path: /products
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          method: get
          path: /products/{productId}
          cors: true
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          method: post
          path: /products
          cors: true
          request:
              schemas:
                application/json: ${file(src/schemas/createProduct.json)}
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt: [catalogItemsQueue, Arn]
