useDotenv: true

service: authorization-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  profile: aws-training

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
